### ISSUE TITLE
chain icon dark

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/ui#94]
chain icon @Popoulosss 

<img width="849" alt="image" src="https://github.com/opensquare-network/ui/assets/19513289/0d875257-7adf-4b7b-a648-75f1c5f471fd">

_Originally posted by @2nthony in https://github.com/opensquare-network/ui/issues/91#issuecomment-1871828116_

**Comment by Popoulosss** [comment]
Updated @2nthony 

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/ui/assets/59445675/f4d117cd-d3cb-4bef-bf8d-5372617ed63b">

**Comment by Popoulosss** [comment]
Updated @2nthony 

- Shiden
- Altair
- Rococo
- Westmint
- Zeitgeist
- Basilisk
- Hydradx
- Stafi
- Creditcoin
